name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push user-service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest ./user-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest

      - name: Build and push support-ticket-service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/support-ticket-service:latest ./support-ticket-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/support-ticket-service:latest

      - name: Build and push api-gateway
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest ./api-gateway
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
